### PR TITLE
Make simple calibration a package

### PR DESCRIPTION
**Pull request by bobturneruk**
# Chore

**_WHAT DOES THIS PR DO?_**

Makes the code in the folder an installable python package for use in the AirQo-api (https://github.com/airqo-platform/AirQo-api/pull/345)

Long term we may wish to reconsider (again) the location of this code within the AirQo organisation.

**_WHAT JIRA STORY/TASK IS RELATED TO THIS PR?_**

https://airqoteam.atlassian.net/browse/PLAT-523

**_WHAT IS THE LINK TO THE PR BRANCH_**

https://github.com/airqo-platform/AirQo-modules/tree/calibration-simple

**_HOW DO I TEST OUT THIS PR?_**

Follow these instructions:

https://github.com/airqo-platform/AirQo-api/blob/Multi-hop/src/calibrate-multi-hop/readme.md

This will install the code proposed in the pull request into a microservice and test it in that context.

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_**

calibrate-multi-hop

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**

No

**_ARE THERE ANY RELATED PRs?_**

https://github.com/airqo-platform/AirQo-api/pull/345

### CODE REVIEW

**Review by Priscilla-AL — COMMENTED** [review]
Apart from simple.py,  
we shall use dataprocessing.py for getting and processing data and  errormetrics.py for performance evaluation.

**Review by Baalmart — COMMENTED** [review]
Looks good, thanks. 

- I have gone ahead to leave some comments in the [multihop AirQo-api-PR-345](https://github.com/airqo-platform/AirQo-api/pull/345) in the api repo.
- With the current workload and team size, I am already sensing a challenge with reviewing PRs in separate repos, I guess it is just a matter of getting used to.....hopefully!
- I am yet to fully test the outcome, just leaving quick comments....

**Comment by bobturneruk** [comment]
This is now once again a candidate to merge. 

I suggest that the contents of this folder https://github.com/airqo-platform/AirQo-modules/tree/calibration-simple/calibration/simple_calibration would be best managed as a separate repository in the AirQo organisation, and an associated package on PyPi. I suggest that moving it to AirQo-api wouldn't be good as it currently combines functionality needed by both the platform and the data products team.

**Comment by Baalmart** [comment]
> This is now once again a candidate to merge.
> 
> I suggest that the contents of this folder https://github.com/airqo-platform/AirQo-modules/tree/calibration-simple/calibration/simple_calibration would be best managed as a separate repository in the AirQo organisation, and an associated package on PyPi. I suggest that moving it to AirQo-api wouldn't be good as it currently combines functionality needed by both the platform and the data products team.

Sounds good @bobturneruk , I guess we can go ahead with that approach. With the hope that the authors of that repo will actually maintain it. Maintenance (continuous refactoring) of the codebase might be key to keeping the content/repo "alive".

Otherwise, I am all good with your suggestion. :)

**Review by Baalmart — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
