### PR TITLE
Add data model

### PR DESCRIPTION
**Pull request by DennisReddyhoff**
# Pipelining Data Models

**_WHAT DOES THIS PR DO?_**

This PR adds the data_models package, which contains models and controllers for interacting with data and dataframes. Documentation is built with Sphinx and testing uses pytest and tox.

**_WHAT JIRA STORY/TASK IS RELATED TO THIS PR?_**

https://airqoteam.atlassian.net/browse/PLAT-400?atlOrigin=eyJpIjoiMDhjYTA3ZjA2ZmYzNDFkOWExOTE4NmYxYWFiYTcyNDYiLCJwIjoiaiJ9

**_WHAT IS THE LINK TO THE PR BRANCH_**

https://github.com/airqo-platform/AirQo-modules/tree/add-data-model

**_HOW DO I TEST OUT THIS PR?_**

`cd AirQo-modules`
`git checkout add-data-model`

Create and activate a virtual env of your liking (I use conda):

`conda create --name add-data-model python && conda activate add-data-model && hash -r`

Install and run tox:

`pip install tox`
`tox`

If tests pass, there will be an html summary in ./htmlcov.

You can now install from setup.py in your venv:
`pip install -e .`

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_**

No endpoints are currently exposed

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**

**_ARE THERE ANY RELATED PRs?_**

### CODE REVIEW

**Comment by bobturneruk** [comment]
@DennisReddyhoff - can you set this to draft if it's not ready for review, yet, please?

**Comment by bobturneruk** [comment]
Do you plan to use readthedocs or GitHub pages? Readthedocs would get the html etc. out of the repo...

**Comment by bobturneruk** [comment]
I guess implicit in this is that there's a single set of docs for all of the modules.

**Comment by DennisReddyhoff** [comment]
> Do you plan to use readthedocs or GitHub pages? Readthedocs would get the html etc. out of the repo...

The repo is private so readthedocs would require a subscription

**Comment by bobturneruk** [comment]
Are you sure it's private? I can see it in an incognito window...

**Comment by DennisReddyhoff** [comment]
Questions to answer:

docs: 

- Move to readthedocs? Requires action by repo admin
- docstring formatting, I used Google/PEP8, sphinx accepts rst, Google, Numpy and more
- typehints: I've used them because I like them, but it means the code won't work with Python 2

tests: 

- Integration with Jenkins?
- Requirements? We could have requirements.txt files in each package and then scrape them and use in setup.py?

**Comment by Baalmart** [comment]
I do not think the repo is private....
> Are you sure it's private? I can see it in an incognito window...

**Comment by bobturneruk** [comment]
I'll try and answer some questions!

> Move to readthedocs? Requires action by repo admin

Good idea - this PR has a load of content that is just the built site and it's hard to see what's going on. Readthedocs will need a hook set up so that the readthedocs site knows when something changes. The actual cloning and building of the docs then happens off github.

> docstring formatting, I used Google/PEP8, sphinx accepts rst, Google, Numpy and more

Great. Please document this choice somewhere (readme / contributing) and everyone can adopt it (unless there are objections). Key thing is to pick something that basically works for us and stick with it.

> typehints: I've used them because I like them, but it means the code won't work with Python 2

Python 2 is no longer officially supported. If there is no compelling project reason to support python 2 (@Baalmart), we should not support it either. We need to decide as a team if typehints are optional or mandatory in our code and document this in readme / contributing. 

> Integration with Jenkins?

I suggest GitHub actions is used to run tests on this repository. These can be triggered by pushes and pull requests. We should not allow merges to staging without passing tests. This probably makes tox unnecessary. Test coverage should be reported. However, all this should be a seperate issue(s) so as not to delay this PR. I can help implement this stuff.

> Requirements? We could have requirements.txt files in each package and then scrape them and use in setup.py?

Are we having a single `setup.py` for the whole repo? I think it's fine to "hard code" requirements in `setup.py` for now.

**Review by lilly-muyama — APPROVED** [review]

**Review by sserurich — APPROVED** [review]
looks good

**Review by Priscilla-AL — COMMENTED** [review]
First got this error ModuleNotFoundError: No module named 'pandas'.
After I remove the pandas version I get the error below.

===================================== 2 errors in 0.36s ======================================= 
ERROR: InvocationError for command 'C:\Users\User\Documents\Projects\AirQo-models\.tox\py37\Scripts\pytest.EXE' --cov '.tox\py37\Lib\site-packages\data_models' --cov-report term-missing (exited 
with code 2)
___________________________________________ summary ____________________________________________ 
ERROR:   py37: commands failed

**Review by Baalmart — APPROVED** [review]
All runs as described in the PR, thanks. :) 

Just a few comments for consideration as we proceed...
- I guess we might have to separate the requirements in one way or another
- As for the tests, could we explore having them close to the folder (package/module) they are testing. When the test files are relatively far away from the files they are testing, it can get tricky accessing them for modifications as the codebase increases. Just a convention to consider but no big deal...
- Otherwise, I hope these docs files wont be appearing in most of the future PRs, makes the PR kinda big (file changes) in case it is not a "setup" PR. :)
- 
Thanks again!

**Pull request merged**
