### PR TITLE
Organisational file structure for the ML modules repo

### PR DESCRIPTION
**Pull request by Baalmart**
# Chore

**_WHAT DOES THIS PR DO?_**

- [ ] Introduces the initial file organisational structure for the ML modules/packages repo
- [ ] Also adds template files for PR, feature requests and issues

**_WHAT JIRA STORY/TASK IS RELATED TO THIS PR?_**
N/A

**_WHAT IS THE LINK TO THE PR BRANCH_**
https://github.com/airqo-platform/AirQo-modules/tree/structure-files

**_HOW DO I TEST OUT THIS PR?_**
N/A

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 
N/A

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**
N/A

**_ARE THERE ANY RELATED PRs?_**
N/A

### CODE REVIEW

**Review by bobturneruk — APPROVED** [review]
Good stuff @Baalmart and others! A few suggestions that could make it better (or become issues on Jira to be picked up in the next sprint?).

- Edit readme to explain new folder structure (referring to the api repo. readme / wiki where appropriate).
- Brief readmes for `calibration`, `data` and `spatial`.
- Statement on how we want dependencies to be managed (e.g. `requirements.txt` at module level i.e. `calibration/requirements.txt`, `data/requirements.txt`, `models/requirements.txt`).
- Basic structure for tests in each module (e.g. `calibration/controllers/tests` and `calibration/models/tests`, or `calibration/tests`) - this will mostly be new code so tests should be written alongside it so users can have confidence in platform outputs.
- Link to contributing guidelines (api wiki).

Statement on issues - do we want to switch issues off in this repo. and channel everything through support->Jira?

**Comment by Baalmart** [comment]
Thanks @bobturneruk , shall embark on feedback items accordingly! :) 

> Good stuff @Baalmart and others! A few suggestions that could make it better (or become issues on Jira to be picked up in the next sprint?).
> 
> * Edit readme to explain new folder structure (referring to the api repo. readme / wiki where appropriate).
> * Brief readmes for `calibration`, `data` and `spatial`.
> * Statement on how we want dependencies to be managed (e.g. `requirements.txt` at module level i.e. `calibration/requirements.txt`, `data/requirements.txt`, `models/requirements.txt`).
> * Basic structure for tests in each module (e.g. `calibration/controllers/tests` and `calibration/models/tests`, or `calibration/tests`) - this will mostly be new code so tests should be written alongside it so users can have confidence in platform outputs.
> * Link to contributing guidelines (api wiki).
> 
> Statement on issues - do we want to switch issues off in this repo. and channel everything through support->Jira?

**Comment by DennisReddyhoff** [comment]
I've started on the file structure, I think this would be ok as a base to work on a MVP that we can take further?

**Comment by Baalmart** [comment]
"MVP" sounds good to me. :)  @DennisReddyhoff 
> I've started on the file structure, I think this would be ok as a base to work on a MVP that we can take further?

**Review by DennisReddyhoff — APPROVED** [review]
I think we can move on with this basic structure, I will open a new PR for implementing a DataModel so we can move this along.

**Review by danielogen — APPROVED** [review]
Hi @Baalmart, this looks great. Just a quick question; where do we put model testing functionality...just being curious :)

**Comment by bobturneruk** [comment]
@Baalmart Perhaps some of the points I made not picked up on in this PR should become Jira issues? I could add them? Without testing and assurance of reproducibility through dependency / execution environment management, there can't be an MVP.

**Comment by DennisReddyhoff** [comment]
> @Baalmart Perhaps some of the points I made not picked up on in this PR should become Jira issues? I could add them? Without testing and assurance of reproducibility through dependency / execution environment management, there can't be an MVP.

Sounds good Bob thanks, I've added folders for tests in each sub directory and Readme's. This isn't the MVP, just a v1 folder structure for it. I will add a new PR (or should we just use Jira?) for adding a basic data model which we can then use to answer your other questions.

**Pull request merged**
